name: CI

on:
  push:
    branches: [main]

env:
  REPO: ${{ secrets.DOCKER_HUB_USERNAME }}/movie-list

jobs:
  build-push-to-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push (${{ github.ref_name }})
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.REPO }}:latest
          cache-from: type=registry,ref=${{ env.REPO }}:buildcache
          cache-to: type=registry,ref=${{ env.REPO }}:buildcache,mode=max
      - name: Recreate portainer container
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.PORTAINER_WEBHOOK_URL }}
          method: 'POST'
